[book]
title = "Nixy"
authors = ["anialic"]
language = "en"
src = "docs"

[build]
build-dir = "book"

[output.html]
default-theme = "coal"
preferred-dark-theme = "coal"
no-section-label = true

smart-punctuation = true
copy-fonts = true
mathjax-support = false

git-repository-url = "https://github.com/anialic/nixy"
edit-url-template = "https://github.com/anialic/nixy/edit/main/{path}"
search.use-boolean-and = true

curly-quotes = true
